# Generated by Django 4.2.6 on 2023-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_executive_date_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveposition',
            name='name',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('committee Member', 'committee Member')], max_length=30, unique=True),
        ),
    ]
