# Generated by Django 4.2.6 on 2023-10-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_executiveposition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='executive_images/'),
        ),
    ]
