# Generated by Django 4.2.6 on 2023-11-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_document_date_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_received',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='date_sent',
        ),
    ]
