# Generated by Django 4.2.6 on 2024-03-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_document_status_alter_document_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
