# Generated by Django 4.2.6 on 2024-03-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_comment_document_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='message',
            new_name='description',
        ),
    ]
