# Generated by Django 4.2.6 on 2024-05-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_message_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_group',
            field=models.CharField(default='ALL', max_length=20),
        ),
    ]
