# Generated by Django 4.2.6 on 2024-05-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_announcement_target_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_group',
            field=models.CharField(choices=[('ALL', 'All'), ('MEMBERS', 'Members'), ('EXECUTIVES', 'Executives')], default='ALL', max_length=20),
        ),
    ]
