# Generated by Django 4.2.6 on 2024-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_readannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(related_name='files', to='dashboard.file'),
        ),
    ]
