# Generated by Django 4.2.6 on 2024-05-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_document_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(to='dashboard.file'),
        ),
    ]
