# Generated by Django 4.2.6 on 2024-07-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_event_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='publisher',
        ),
    ]
