# Generated by Django 4.2.6 on 2024-07-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_event_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
