# Generated by Django 4.2.6 on 2024-07-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0024_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_group',
        ),
        migrations.AddField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('specific_groups', 'Specific Groups')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('selected_groups', 'Selected Groups')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
