# Generated by Django 4.2.6 on 2024-07-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_announcement_target_group_announcement_target_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executive',
        ),
        migrations.DeleteModel(
            name='ExecutivePosition',
        ),
    ]
