# Generated by Django 4.2.6 on 2024-12-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadAnnouncement',
        ),
    ]
