# Generated by Django 4.2.6 on 2025-08-08 08:46

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_alter_news_featured_image_alter_news_news_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("presentation_title", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_speakers/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_date", "-start_time"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.RenameField(
            model_name="event",
            old_name="image",
            new_name="featured_image",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="is_past_due",
            new_name="is_featured",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="time",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="cpd_credits",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Continuing Professional Development credits",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("conference", "Conference"),
                    ("workshop", "Workshop"),
                    ("meeting", "Meeting"),
                    ("seminar", "Seminar"),
                    ("lecture", "Lecture"),
                    ("social", "Social Event"),
                    ("other", "Other"),
                ],
                default="meeting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="expected_participants",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="location_url",
            field=models.URLField(blank=True, help_text="Google Maps URL or similar"),
        ),
        migrations.AddField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="0 means unlimited"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_url",
            field=models.URLField(
                blank=True, help_text="External registration link if applicable"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="short_description",
            field=models.TextField(
                default="test description",
                help_text="Brief description for listings (max 200 chars)",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("postponed", "Postponed"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, to="dashboard.tag"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=tinymce.models.HTMLField(help_text="Full event description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="EventScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="dashboard.event",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="event_images/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="dashboard.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EventDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="event_documents/")),
                ("is_public", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dashboard.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="dashboard.eventspeaker"
            ),
        ),
    ]
