# Generated by Django 4.2.6 on 2025-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_eventspeaker_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="access_code",
            field=models.CharField(
                blank=True, help_text="Access code for the online event", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_online",
            field=models.BooleanField(
                default=False, help_text="Check if the event is online"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="online_link",
            field=models.URLField(
                blank=True, help_text="Link to join the online event"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="online_platform",
            field=models.CharField(
                blank=True, help_text="e.g., Zoom, Microsoft Teams", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("conference", "Conference"),
                    ("workshop", "Workshop"),
                    ("meeting", "Meeting"),
                    ("seminar", "Seminar"),
                    ("lecture", "Lecture"),
                    ("social", "Social Event"),
                    ("online", "Online Event"),
                    ("other", "Other"),
                ],
                default="meeting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.CharField(
                blank=True, help_text="Leave blank for online events", max_length=100
            ),
        ),
    ]
