# Generated by Django 4.2.6 on 2025-10-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0033_event_access_code_event_is_online_event_online_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
