# Generated by Django 4.2.6 on 2025-10-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_advertplan"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdvertPlan",
        ),
    ]
