# Generated by Django 4.2.6 on 2026-01-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_delete_advertplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="news_slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
