# Generated by Django 4.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_alter_news_news_slug_alter_news_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photos_link",
            field=models.URLField(
                blank=True,
                help_text="External link to event photos (e.g. Google Photos, Flickr)",
            ),
        ),
    ]
