import {
  Bell,
  BadgeDollarSign,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardCheck,
  FileClock,
  FileText,
  Flag,
  GalleryHorizontal,
  ImageIcon,
  LayoutDashboard,
  Megaphone,
  MessageSquareText,
  Newspaper,
  PanelsTopLeft,
  ReceiptText,
  Settings2,
  ShieldCheck,
  ToggleRight,
  UserRoundCog,
  Users,
} from "lucide-react";

export const navigation = [
  {
    label: "Overview",
    href: "/dashboard",
    icon: LayoutDashboard,
    permission: "dashboard.view",
    group: "Workspace",
  },
  {
    label: "Members",
    href: "/dashboard/members",
    icon: Users,
    permission: "members.view",
    group: "Association",
  },
  {
    label: "Executives",
    href: "/dashboard/executives",
    icon: BriefcaseBusiness,
    permission: "members.view",
    group: "Association",
  },
  {
    label: "Organization",
    href: "/dashboard/organization",
    icon: Building2,
    permission: "members.view",
    group: "Association",
  },
  {
    label: "Moderation",
    href: "/dashboard/moderation",
    icon: ClipboardCheck,
    permission: "content.publish",
    group: "Publishing",
  },
  {
    label: "News",
    href: "/dashboard/news",
    icon: Newspaper,
    permission: "content.view",
    group: "Publishing",
  },
  {
    label: "Announcements",
    href: "/dashboard/announcements",
    icon: Megaphone,
    permission: "content.view",
    group: "Publishing",
  },
  {
    label: "Events",
    href: "/dashboard/events",
    icon: CalendarDays,
    permission: "dashboard.view",
    group: "Publishing",
  },
  {
    label: "Documents",
    href: "/dashboard/documents",
    icon: FileText,
    permission: "documents.view",
    group: "Knowledge",
  },
  {
    label: "Media",
    href: "/dashboard/media",
    icon: ImageIcon,
    permission: "media.manage",
    group: "Knowledge",
  },
  {
    label: "Galleries",
    href: "/dashboard/galleries",
    icon: GalleryHorizontal,
    permission: "content.view",
    group: "Knowledge",
  },
  {
    label: "Homepage carousel",
    href: "/dashboard/carousel",
    icon: PanelsTopLeft,
    permission: "settings.manage",
    group: "Publishing",
  },
  {
    label: "Notifications",
    href: "/dashboard/notifications",
    icon: Bell,
    permission: "dashboard.view",
    group: "Communications",
  },
  {
    label: "Chat",
    href: "/dashboard/chat",
    icon: MessageSquareText,
    permission: "chat.use",
    group: "Communications",
  },
  {
    label: "Adverts",
    href: "/dashboard/adverts",
    icon: Flag,
    permission: "adverts.manage",
    group: "Operations",
  },
  {
    label: "Advert placements",
    href: "/dashboard/advert-slots",
    icon: PanelsTopLeft,
    permission: "adverts.manage",
    group: "Operations",
  },
  {
    label: "Advert plans",
    href: "/dashboard/advert-plans",
    icon: BadgeDollarSign,
    permission: "adverts.manage",
    group: "Operations",
  },
  {
    label: "Advert orders",
    href: "/dashboard/advert-orders",
    icon: ReceiptText,
    permission: "adverts.manage",
    group: "Operations",
  },
  {
    label: "Analytics",
    href: "/dashboard/analytics",
    icon: ChartNoAxesCombined,
    permission: "analytics.view",
    group: "Operations",
  },
  {
    label: "Audit",
    href: "/dashboard/audit",
    icon: ShieldCheck,
    permission: "audit.view",
    group: "Operations",
  },
  {
    label: "Jobs",
    href: "/dashboard/jobs",
    icon: FileClock,
    permission: "jobs.manage",
    group: "Operations",
  },
  {
    label: "Settings",
    href: "/dashboard/settings",
    icon: Settings2,
    permission: "settings.manage",
    group: "Operations",
  },
  {
    label: "Feature flags",
    href: "/dashboard/feature-flags",
    icon: ToggleRight,
    permission: "settings.manage",
    group: "Operations",
  },
  {
    label: "Profile",
    href: "/dashboard/profile",
    icon: UserRoundCog,
    permission: "dashboard.view",
    group: "Account",
  },
] as const;

export type NavItem = (typeof navigation)[number];
