# Generated by Django 4.2.6 on 2024-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
    ]
