# Generated by Django 4.2.6 on 2024-07-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_admin_remove_user_is_executive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view dashboard')]},
        ),
    ]
