# Generated by Django 4.2.6 on 2024-07-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_admins', 'Can view admins'), ('view_members', 'Can view members'), ('view_executives', 'Can view executives')]},
        ),
    ]
