# Generated by Django 4.2.6 on 2024-07-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_appointed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='executive_image',
            field=models.ImageField(blank=True, null=True, upload_to='executive_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='executive_position',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Committee Member', 'Committee Member')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fb_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
