# Generated by Django 4.2.6 on 2024-07-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('add_admins', 'Can add admin'), ('change_admins', 'Can change admin'), ('delete_admins', 'Can delete admin'), ('view_admin', 'Can view admin'), ('add_executive', 'Can add executive'), ('change_executive', 'Can change executive'), ('delete_executive', 'Can delete executive'), ('view_executive', 'Can view executive'), ('add_member', 'Can add member'), ('change_member', 'Can change member'), ('delete_member', 'Can delete member'), ('view_member', 'Can view member')]},
        ),
    ]
