# Generated by Django 4.2.6 on 2024-12-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_is_bulk_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
