# Generated by Django 4.2.6 on 2025-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='executive_position',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ("Women's Executive\xa0Officer", "Women's Executive\xa0Officer"), ('Past President', 'Past President'), ('CBAS\xa0Rep', 'CBAS\xa0Rep'), ('College of Humanities\xa0Rep', 'College of Humanities\xa0Rep'), ('College of Health\xa0Rep', 'College of Health\xa0Rep')], max_length=30, null=True),
        ),
    ]
