# Generated by Django 4.2.6 on 2025-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_executive_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Prof.', 'Prof.'), ('Prof. (Mrs.)', 'Prof. (Mrs.)'), ('Dr.', 'Dr.'), ('Dr. (Alhaji)', 'Dr. (Alhaji)'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=15),
        ),
    ]
