# Generated by Django 4.2.6 on 2025-10-04 04:16

from django.db import migrations, models
import random
import string


def generate_unique_staff_ids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    existing = set(
        User.objects.exclude(staff_id__isnull=True).exclude(staff_id__exact='').values_list('staff_id', flat=True)
    )

    def gen():
        return ''.join(random.choices(string.digits, k=6))

    for user in User.objects.all():
        if not user.staff_id:
            val = gen()
            while val in existing:
                val = gen()
            user.staff_id = val
            existing.add(val)
            user.save(update_fields=['staff_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_college_school_rename_last_name_user_surname_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_unique_staff_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="staff_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
