# Generated by Django 4.2.6 on 2025-10-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="other_name",
            field=models.CharField(default="Esther", max_length=30),
            preserve_default=False,
        ),
    ]
