# Generated by Django 4.2.6 on 2025-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_user_other_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.AddField(
            model_name="user",
            name="executive_terms",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
