# Generated by Django 4.2.6 on 2025-10-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_remove_user_first_name_user_executive_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
