# Generated by Django 4.2.6 on 2026-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_rename_rank_to_academic_rank"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="academic_rank",
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
