# Generated by Django 4.2.6 on 2026-01-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_add_executive_bio_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="executive_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("President", "President"),
                    ("Vice President", "Vice President"),
                    ("Secretary", "Secretary"),
                    ("Treasurer", "Treasurer"),
                    ("Women's Executive\xa0Officer", "Women's Executive\xa0Officer"),
                    ("Past President", "Past President"),
                    ("National President", "National President"),
                    ("CBAS\xa0Rep", "CBAS\xa0Rep"),
                    ("College of Humanities\xa0Rep", "College of Humanities\xa0Rep"),
                    ("College of Health\xa0Rep", "College of Health\xa0Rep"),
                    ("College of Education Rep", "College of Education Rep"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
