# Generated by Django 4.2.6 on 2026-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_user_executive_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                choices=[
                    ("Prof.", "Prof."),
                    ("Prof. (Mrs.)", "Prof. (Mrs.)"),
                    ("Dr.", "Dr."),
                    ("Dr. (Mrs.)", "Dr. (Mrs.)"),
                    ("Dr. (Miss)", "Dr. (Miss)"),
                    ("Mr.", "Mr."),
                    ("Mrs.", "Mrs."),
                    ("Miss", "Miss"),
                    ("Ms.", "Ms."),
                    ("Mx.", "Mx."),
                    ("Rev.", "Rev."),
                    ("Hon.", "Hon."),
                    ("Eng.", "Eng."),
                    ("Sir", "Sir"),
                    ("Dame", "Dame"),
                ],
                max_length=15,
            ),
        ),
    ]
