# Generated by Django 4.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_alter_user_title"),
        ("accounts", "0032_migrate_executive_position_names"),
    ]

    operations = [
    ]
