# Generated by Django 4.2.6 on 2026-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0033_merge_0032_alter_user_title_0032_migrate_executive_position_names",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="executive_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("President", "President"),
                    ("Vice President", "Vice President"),
                    ("Secretary", "Secretary"),
                    ("Treasurer", "Treasurer"),
                    ("Women's Executive\xa0Officer", "Women's Executive\xa0Officer"),
                    ("National President", "National President"),
                    ("CBAS Rep", "CBAS Rep"),
                    ("CHS Rep", "CHS Rep"),
                    ("COE Rep", "COE Rep"),
                    ("COH Rep", "COH Rep"),
                    ("College of Humanities Rep", "College of Humanities Rep"),
                    ("College of Health Rep", "College of Health Rep"),
                    ("College of Education Rep", "College of Education Rep"),
                    ("Past President", "Past President"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
