# Generated by Django 4.2.6 on 2025-10-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_add_thumbnail_paths"),
        ("chat", "0005_add_thumbnail_paths"),
    ]

    operations = []
