# Generated by Django 4.2.6 on 2026-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_groupmembership_is_admin_groupmessage_reply_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgroup",
            name="invite_token",
            field=models.CharField(
                db_index=True,
                default="dsfhdshfsfsdfsdf",
                editable=False,
                max_length=64,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
