# Generated by Django 4.2.6 on 2026-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chatthread_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgroup",
            name="access_token",
            field=models.CharField(
                db_index=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
