# Generated by Django 4.2.6 on 2024-05-02 18:26

import adverts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=adverts.models.upload_to),
        ),
    ]
