# Generated by Django 4.2.6 on 2024-05-04 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_rename_name_advertiser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
