# Generated by Django 4.2.6 on 2025-01-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('sidebar', 'Sidebar'), ('bottom', 'Bottom')], default='top', help_text='Select the ad position for this advertisement.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertplan',
            name='positions',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('sidebar', 'Sidebar'), ('bottom', 'Bottom')], help_text='Select the positions available for this plan.', max_length=100),
        ),
        migrations.AlterField(
            model_name='advertplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
