# Generated by Django 4.2.6 on 2025-10-18 22:03

import adverts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0008_advertisement_position_advertplan_positions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "recommended_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "recommended_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="advertplan",
            name="positions",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="cta_text",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="desktop_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=adverts.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="html_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="impressions_cap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="impressions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="mobile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=adverts.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="priority",
            field=models.SmallIntegerField(
                default=0, help_text="Higher value = higher priority when rendering"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[("top", "Top"), ("sidebar", "Sidebar"), ("bottom", "Bottom")],
                help_text="Legacy: Select the ad position for this advertisement. Use placements for new campaigns.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="placements",
            field=models.ManyToManyField(
                blank=True, related_name="adverts", to="adverts.placement"
            ),
        ),
    ]
