# Generated by Django 4.2.6 on 2025-10-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0010_migrate_positions_to_placements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="position",
        ),
    ]
