# Generated by Django 4.2.6 on 2025-10-19 07:49

import adverts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0012_create_default_placements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=140)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=adverts.models.ad_upload_to
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("html_content", models.TextField(blank=True, null=True)),
                ("target_url", models.URLField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=0, help_text="Higher number = higher priority"
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.RemoveField(
            model_name="advertiser",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="advert",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="advertiser",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="plan",
        ),
        migrations.DeleteModel(
            name="Advertisement",
        ),
        migrations.DeleteModel(
            name="Advertiser",
        ),
        migrations.DeleteModel(
            name="AdvertPlan",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Placement",
        ),
        migrations.AddField(
            model_name="ad",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="adverts.adslot",
            ),
        ),
    ]
