# Generated by Django 4.2.6 on 2025-01-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the gallery', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the gallery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the gallery was created')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload image file', upload_to='gallery_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the image was uploaded')),
                ('gallery', models.ForeignKey(help_text='Gallery this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallery')),
            ],
        ),
    ]
