# Generated by Django 4.2.6 on 2025-01-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the gallery is active'),
        ),
    ]
