"""initial modern portal schema

Revision ID: 3c1031d8689f
Revises:
Create Date: 2026-07-22 16:14:46.586116
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3c1031d8689f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_plans",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_plans")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_ad_plans_legacy_id")),
    )
    op.create_table(
        "ad_slots",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_slots")),
        sa.UniqueConstraint("key", name=op.f("uq_ad_slots_key")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_ad_slots_legacy_id")),
    )
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
        sa.UniqueConstraint("key", name=op.f("uq_feature_flags_key")),
    )
    op.create_table(
        "galleries",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=260), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_galleries")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_galleries_legacy_id")),
    )
    op.create_index(op.f("ix_galleries_slug"), "galleries", ["slug"], unique=True)
    op.create_index(op.f("ix_galleries_status"), "galleries", ["status"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=150), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("credit", sa.String(length=250), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_media_assets_legacy_id")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_assets_storage_key")),
    )
    op.create_index(op.f("ix_media_assets_sha256"), "media_assets", ["sha256"], unique=False)
    op.create_index(op.f("ix_media_assets_status"), "media_assets", ["status"], unique=False)
    op.create_table(
        "migration_dispositions",
        sa.Column("batch_id", sa.String(length=100), nullable=False),
        sa.Column("source_table", sa.String(length=180), nullable=False),
        sa.Column("source_pk", sa.String(length=180), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("disposition", sa.String(length=30), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=True),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("archive_key", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_migration_dispositions")),
        sa.UniqueConstraint("source_table", "source_pk", name="migration_source_record"),
    )
    op.create_index(
        op.f("ix_migration_dispositions_batch_id"),
        "migration_dispositions",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_migration_dispositions_disposition"),
        "migration_dispositions",
        ["disposition"],
        unique=False,
    )
    op.create_index(
        op.f("ix_migration_dispositions_source_table"),
        "migration_dispositions",
        ["source_table"],
        unique=False,
    )
    op.create_table(
        "organization_units",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("unit_type", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organization_units.id"],
            name=op.f("fk_organization_units_parent_id_organization_units"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_units")),
        sa.UniqueConstraint("slug", name=op.f("uq_organization_units_slug")),
        sa.UniqueConstraint("unit_type", "legacy_id", name="organization_legacy_identity"),
        sa.UniqueConstraint("unit_type", "name", "parent_id", name="unit_identity"),
    )
    op.create_index(
        op.f("ix_organization_units_parent_id"), "organization_units", ["parent_id"], unique=False
    )
    op.create_index(
        "ix_organization_units_parent_type",
        "organization_units",
        ["parent_id", "unit_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_units_unit_type"), "organization_units", ["unit_type"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("topic", sa.String(length=250), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_created_at"), "outbox_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_event_type"), "outbox_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_topic"), "outbox_events", ["topic"], unique=False)
    op.create_index(
        "ix_outbox_unpublished", "outbox_events", ["published_at", "created_at"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
    )
    op.create_index(op.f("ix_permissions_key"), "permissions", ["key"], unique=True)
    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_key"), "roles", ["key"], unique=True)
    op.create_table(
        "site_settings",
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_site_settings_key")),
    )
    op.create_table(
        "users",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("staff_id", sa.String(length=40), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("other_name", sa.String(length=120), nullable=False),
        sa.Column("surname", sa.String(length=120), nullable=False),
        sa.Column("gender", sa.String(length=30), nullable=True),
        sa.Column("academic_rank", sa.String(length=120), nullable=True),
        sa.Column("phone_number", sa.String(length=40), nullable=True),
        sa.Column("profile_media_id", sa.Uuid(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=True),
        sa.Column("college_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["organization_units.id"],
            name=op.f("fk_users_college_id_organization_units"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["organization_units.id"],
            name=op.f("fk_users_department_id_organization_units"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_media_id"],
            ["media_assets.id"],
            name=op.f("fk_users_profile_media_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["organization_units.id"],
            name=op.f("fk_users_school_id_organization_units"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_users_legacy_id")),
    )
    op.create_index(op.f("ix_users_college_id"), "users", ["college_id"], unique=False)
    op.create_index(op.f("ix_users_department_id"), "users", ["department_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_name", "users", ["surname", "other_name"], unique=False)
    op.create_index(op.f("ix_users_school_id"), "users", ["school_id"], unique=False)
    op.create_index(op.f("ix_users_staff_id"), "users", ["staff_id"], unique=True)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index("ix_users_status_created", "users", ["status", "created_at"], unique=False)
    op.create_foreign_key(
        op.f("fk_media_assets_owner_id_users"),
        "media_assets",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "account_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_account_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_tokens")),
    )
    op.create_index(
        op.f("ix_account_tokens_expires_at"), "account_tokens", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_account_tokens_kind"), "account_tokens", ["kind"], unique=False)
    op.create_index(
        op.f("ix_account_tokens_token_hash"), "account_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_account_tokens_used_at"), "account_tokens", ["used_at"], unique=False)
    op.create_index(op.f("ix_account_tokens_user_id"), "account_tokens", ["user_id"], unique=False)
    op.create_table(
        "ad_campaigns",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=True),
        sa.Column("target_url", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_ad_campaigns_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_ad_campaigns_media_asset_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["ad_slots.id"],
            name=op.f("fk_ad_campaigns_slot_id_ad_slots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_campaigns")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_ad_campaigns_legacy_id")),
    )
    op.create_index(op.f("ix_ad_campaigns_slot_id"), "ad_campaigns", ["slot_id"], unique=False)
    op.create_index(op.f("ix_ad_campaigns_status"), "ad_campaigns", ["status"], unique=False)
    op.create_table(
        "announcements",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("content_html", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("audiences", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_announcements_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_announcements_legacy_id")),
    )
    op.create_index(op.f("ix_announcements_status"), "announcements", ["status"], unique=False)
    op.create_index(
        "ix_announcements_status_published",
        "announcements",
        ["status", "published_at"],
        unique=False,
    )
    op.create_table(
        "articles",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=260), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("content_html", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("featured_media_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_articles_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["featured_media_id"],
            ["media_assets.id"],
            name=op.f("fk_articles_featured_media_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_articles_legacy_id")),
    )
    op.create_index(op.f("ix_articles_slug"), "articles", ["slug"], unique=True)
    op.create_index(op.f("ix_articles_status"), "articles", ["status"], unique=False)
    op.create_index(
        "ix_articles_status_published", "articles", ["status", "published_at"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=150), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_resource_type"), "audit_events", ["resource_type"], unique=False
    )
    op.create_index(
        "ix_audit_resource_created",
        "audit_events",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "background_jobs",
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_background_jobs_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_jobs")),
    )
    op.create_index(op.f("ix_background_jobs_kind"), "background_jobs", ["kind"], unique=False)
    op.create_index(
        op.f("ix_background_jobs_owner_id"), "background_jobs", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_background_jobs_status"), "background_jobs", ["status"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("direct_key", sa.String(length=80), nullable=True),
        sa.Column("title", sa.String(length=180), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("encryption_key_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("encryption_key_version", sa.String(length=80), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_conversations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_conversations_legacy_id")),
    )
    op.create_index(
        op.f("ix_conversations_direct_key"), "conversations", ["direct_key"], unique=True
    )
    op.create_index(op.f("ix_conversations_kind"), "conversations", ["kind"], unique=False)
    op.create_index(
        op.f("ix_conversations_last_message_at"), "conversations", ["last_message_at"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("public_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("sender", sa.String(length=250), nullable=True),
        sa.Column("receiver", sa.String(length=250), nullable=True),
        sa.Column("description_html", sa.Text(), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("audiences", sa.JSON(), nullable=False),
        sa.Column("retention_class", sa.String(length=80), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_documents_legacy_id")),
    )
    op.create_index(op.f("ix_documents_public_id"), "documents", ["public_id"], unique=True)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(
        "ix_documents_status_category", "documents", ["status", "category"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=260), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("description_json", sa.JSON(), nullable=False),
        sa.Column("description_html", sa.Text(), nullable=False),
        sa.Column("featured_media_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("publication_status", sa.String(length=30), nullable=False),
        sa.Column("venue", sa.String(length=250), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("location_url", sa.String(length=1000), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("online_platform", sa.String(length=120), nullable=True),
        sa.Column("online_link_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("access_code_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("registration_required", sa.Boolean(), nullable=False),
        sa.Column("registration_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_participants", sa.Integer(), nullable=True),
        sa.Column("expected_participants", sa.Integer(), nullable=True),
        sa.Column("cpd_credits", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("organizer", sa.JSON(), nullable=False),
        sa.Column("speakers", sa.JSON(), nullable=False),
        sa.Column("schedule", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_events_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["featured_media_id"],
            ["media_assets.id"],
            name=op.f("fk_events_featured_media_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_events_legacy_id")),
    )
    op.create_index(
        op.f("ix_events_publication_status"), "events", ["publication_status"], unique=False
    )
    op.create_index(op.f("ix_events_slug"), "events", ["slug"], unique=True)
    op.create_index(op.f("ix_events_start_date"), "events", ["start_date"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_index("ix_events_status_start", "events", ["status", "start_date"], unique=False)
    op.create_table(
        "executive_appointments",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.String(length=120), nullable=False),
        sa.Column("portfolio", sa.String(length=180), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("biography_html", sa.Text(), nullable=True),
        sa.Column("social_links", sa.JSON(), nullable=False),
        sa.Column("appointed_on", sa.Date(), nullable=True),
        sa.Column("ended_on", sa.Date(), nullable=True),
        sa.Column("term_number", sa.Integer(), nullable=False),
        sa.Column("is_acting", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_executive_appointments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executive_appointments")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_executive_appointments_legacy_id")),
    )
    op.create_index(
        "ix_executive_active_position",
        "executive_appointments",
        ["position", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executive_appointments_position"),
        "executive_appointments",
        ["position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executive_appointments_user_id"),
        "executive_appointments",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "gallery_items",
        sa.Column("gallery_id", sa.Uuid(), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gallery_id"],
            ["galleries.id"],
            name=op.f("fk_gallery_items_gallery_id_galleries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_gallery_items_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gallery_items")),
        sa.UniqueConstraint("gallery_id", "position", name="gallery_position"),
    )
    op.create_index(
        op.f("ix_gallery_items_gallery_id"), "gallery_items", ["gallery_id"], unique=False
    )
    op.create_index(
        op.f("ix_gallery_items_media_asset_id"), "gallery_items", ["media_asset_id"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_idempotency_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("user_id", "key", name="user_idempotency_key"),
    )
    op.create_index(
        op.f("ix_idempotency_records_expires_at"),
        "idempotency_records",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_user_id"), "idempotency_records", ["user_id"], unique=False
    )
    op.create_table(
        "media_variants",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("variant", sa.String(length=80), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=150), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["media_assets.id"],
            name=op.f("fk_media_variants_asset_id_media_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_variants")),
        sa.UniqueConstraint("asset_id", "variant", name="asset_variant"),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_variants_storage_key")),
    )
    op.create_index(
        op.f("ix_media_variants_asset_id"), "media_variants", ["asset_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("deep_link", sa.String(length=1000), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_notifications_legacy_id")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index(
        "ix_notifications_user_read_created",
        "notifications",
        ["user_id", "read_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=False),
        sa.Column("ip_prefix", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_revoked_at"), "sessions", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.String(length=180), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
            name=op.f("fk_user_roles_assigned_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role_id", name="user_role"),
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "ad_orders",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["ad_campaigns.id"],
            name=op.f("fk_ad_orders_campaign_id_ad_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["ad_plans.id"],
            name=op.f("fk_ad_orders_plan_id_ad_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ad_orders_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_orders")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_ad_orders_legacy_id")),
    )
    op.create_index(op.f("ix_ad_orders_status"), "ad_orders", ["status"], unique=False)
    op.create_index(op.f("ix_ad_orders_user_id"), "ad_orders", ["user_id"], unique=False)
    op.create_table(
        "conversation_members",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_muted", sa.Boolean(), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_members_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversation_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_members")),
        sa.UniqueConstraint("conversation_id", "user_id", name="conversation_user"),
    )
    op.create_index(
        op.f("ix_conversation_members_conversation_id"),
        "conversation_members",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_members_user_id"), "conversation_members", ["user_id"], unique=False
    )
    op.create_table(
        "document_files",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_files_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_document_files_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_document_files_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_files")),
        sa.UniqueConstraint("document_id", "version_number", name="document_version"),
    )
    op.create_index(
        op.f("ix_document_files_document_id"), "document_files", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_files_media_asset_id"), "document_files", ["media_asset_id"], unique=False
    )
    op.create_table(
        "event_registrations",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_registrations_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_event_registrations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_registrations")),
        sa.UniqueConstraint("event_id", "user_id", name="event_user_registration"),
    )
    op.create_index(
        op.f("ix_event_registrations_event_id"), "event_registrations", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_registrations_user_id"), "event_registrations", ["user_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("client_message_id", sa.String(length=100), nullable=False),
        sa.Column("reply_to_id", sa.Uuid(), nullable=True),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.String(length=80), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["users.id"],
            name=op.f("fk_messages_deleted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["messages.id"],
            name=op.f("fk_messages_reply_to_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("fk_messages_sender_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("legacy_id", name=op.f("uq_messages_legacy_id")),
        sa.UniqueConstraint("sender_id", "client_message_id", name="sender_client_message"),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_table(
        "message_receipts",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_receipts_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_message_receipts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", "user_id", name=op.f("pk_message_receipts")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration in non-production environments only."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_receipts")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_event_registrations_user_id"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_event_id"), table_name="event_registrations")
    op.drop_table("event_registrations")
    op.drop_index(op.f("ix_document_files_media_asset_id"), table_name="document_files")
    op.drop_index(op.f("ix_document_files_document_id"), table_name="document_files")
    op.drop_table("document_files")
    op.drop_index(op.f("ix_conversation_members_user_id"), table_name="conversation_members")
    op.drop_index(
        op.f("ix_conversation_members_conversation_id"), table_name="conversation_members"
    )
    op.drop_table("conversation_members")
    op.drop_index(op.f("ix_ad_orders_user_id"), table_name="ad_orders")
    op.drop_index(op.f("ix_ad_orders_status"), table_name="ad_orders")
    op.drop_table("ad_orders")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_revoked_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("role_permissions")
    op.drop_index("ix_notifications_user_read_created", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_media_variants_asset_id"), table_name="media_variants")
    op.drop_table("media_variants")
    op.drop_index(op.f("ix_idempotency_records_user_id"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_expires_at"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_gallery_items_media_asset_id"), table_name="gallery_items")
    op.drop_index(op.f("ix_gallery_items_gallery_id"), table_name="gallery_items")
    op.drop_table("gallery_items")
    op.drop_index(op.f("ix_executive_appointments_user_id"), table_name="executive_appointments")
    op.drop_index(op.f("ix_executive_appointments_position"), table_name="executive_appointments")
    op.drop_index("ix_executive_active_position", table_name="executive_appointments")
    op.drop_table("executive_appointments")
    op.drop_index("ix_events_status_start", table_name="events")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_start_date"), table_name="events")
    op.drop_index(op.f("ix_events_slug"), table_name="events")
    op.drop_index(op.f("ix_events_publication_status"), table_name="events")
    op.drop_table("events")
    op.drop_index("ix_documents_status_category", table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_public_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_conversations_last_message_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_kind"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_direct_key"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_background_jobs_status"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_owner_id"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_kind"), table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index("ix_audit_resource_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_resource_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_articles_status_published", table_name="articles")
    op.drop_index(op.f("ix_articles_status"), table_name="articles")
    op.drop_index(op.f("ix_articles_slug"), table_name="articles")
    op.drop_table("articles")
    op.drop_index("ix_announcements_status_published", table_name="announcements")
    op.drop_index(op.f("ix_announcements_status"), table_name="announcements")
    op.drop_table("announcements")
    op.drop_index(op.f("ix_ad_campaigns_status"), table_name="ad_campaigns")
    op.drop_index(op.f("ix_ad_campaigns_slot_id"), table_name="ad_campaigns")
    op.drop_table("ad_campaigns")
    op.drop_index(op.f("ix_account_tokens_user_id"), table_name="account_tokens")
    op.drop_index(op.f("ix_account_tokens_used_at"), table_name="account_tokens")
    op.drop_index(op.f("ix_account_tokens_token_hash"), table_name="account_tokens")
    op.drop_index(op.f("ix_account_tokens_kind"), table_name="account_tokens")
    op.drop_index(op.f("ix_account_tokens_expires_at"), table_name="account_tokens")
    op.drop_table("account_tokens")
    op.drop_index("ix_users_status_created", table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_staff_id"), table_name="users")
    op.drop_index(op.f("ix_users_school_id"), table_name="users")
    op.drop_index("ix_users_name", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_index(op.f("ix_users_college_id"), table_name="users")
    op.drop_constraint(op.f("fk_media_assets_owner_id_users"), "media_assets", type_="foreignkey")
    op.drop_table("users")
    op.drop_table("site_settings")
    op.drop_index(op.f("ix_roles_key"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_key"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index("ix_outbox_unpublished", table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_topic"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_event_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_created_at"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_organization_units_unit_type"), table_name="organization_units")
    op.drop_index("ix_organization_units_parent_type", table_name="organization_units")
    op.drop_index(op.f("ix_organization_units_parent_id"), table_name="organization_units")
    op.drop_table("organization_units")
    op.drop_index(
        op.f("ix_migration_dispositions_source_table"), table_name="migration_dispositions"
    )
    op.drop_index(
        op.f("ix_migration_dispositions_disposition"), table_name="migration_dispositions"
    )
    op.drop_index(op.f("ix_migration_dispositions_batch_id"), table_name="migration_dispositions")
    op.drop_table("migration_dispositions")
    op.drop_index(op.f("ix_media_assets_status"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_sha256"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_galleries_status"), table_name="galleries")
    op.drop_index(op.f("ix_galleries_slug"), table_name="galleries")
    op.drop_table("galleries")
    op.drop_table("feature_flags")
    op.drop_table("ad_slots")
    op.drop_table("ad_plans")
    # ### end Alembic commands ###
